"""GMAT exam definition and sample questions."""

from scoremap.models import (
    Difficulty,
    ExamDefinition,
    ExamSection,
    ExamType,
    Question,
    QuestionType,
)

GMAT_DEFINITION = ExamDefinition(
    exam_type=ExamType.GMAT,
    name="GMAT Focus Edition",
    description="Graduate Management Admission Test for business school",
    score_range=(205, 805),
    sections=[
        ExamSection(
            name="quantitative",
            topics=[
                "arithmetic",
                "algebra",
                "word_problems",
                "data_sufficiency",
            ],
            time_limit_minutes=45,
            total_questions=21,
            description="Quantitative Reasoning",
        ),
        ExamSection(
            name="verbal",
            topics=[
                "critical_reasoning",
                "reading_comprehension",
                "sentence_correction",
            ],
            time_limit_minutes=45,
            total_questions=23,
            description="Verbal Reasoning",
        ),
        ExamSection(
            name="data_insights",
            topics=[
                "data_interpretation",
                "multi_source_reasoning",
                "table_analysis",
            ],
            time_limit_minutes=45,
            total_questions=20,
            description="Data Insights",
        ),
    ],
)

GMAT_QUESTIONS: list[Question] = [
    # --- Quantitative: Arithmetic ---
    Question(
        id="gmat-quant-001",
        exam_type=ExamType.GMAT,
        section="quantitative",
        topic="arithmetic",
        difficulty=Difficulty.EASY,
        text="What is the greatest common factor of 36 and 48?",
        choices=["6", "8", "12", "24"],
        correct_answer="12",
        explanation="36 = 2^2 * 3^2; 48 = 2^4 * 3. GCF = 2^2 * 3 = 12.",
        time_estimate_seconds=60,
    ),
    Question(
        id="gmat-quant-002",
        exam_type=ExamType.GMAT,
        section="quantitative",
        topic="arithmetic",
        difficulty=Difficulty.MEDIUM,
        text="If a car travels 180 miles in 3 hours and then 240 miles in 4 hours, what is its average speed for the entire trip?",
        choices=["55 mph", "58 mph", "60 mph", "62 mph"],
        correct_answer="60 mph",
        explanation="Total distance = 420 miles. Total time = 7 hours. Speed = 420/7 = 60 mph.",
        time_estimate_seconds=75,
    ),
    Question(
        id="gmat-quant-003",
        exam_type=ExamType.GMAT,
        section="quantitative",
        topic="arithmetic",
        difficulty=Difficulty.HARD,
        text="A tank is filled by pipe A in 6 hours and pipe B in 8 hours. If both pipes are open but there is a leak that drains the tank in 24 hours, how long to fill the tank?",
        choices=["4 hours", "4.8 hours", "5 hours", "5.5 hours"],
        correct_answer="4.8 hours",
        explanation="Combined rate: 1/6 + 1/8 - 1/24 = 4/24 + 3/24 - 1/24 = 6/24 = 1/4... Actually: = 5/24. Time = 24/5 = 4.8 hours.",
        time_estimate_seconds=120,
    ),
    # --- Quantitative: Algebra ---
    Question(
        id="gmat-quant-004",
        exam_type=ExamType.GMAT,
        section="quantitative",
        topic="algebra",
        difficulty=Difficulty.EASY,
        text="If y = 2x + 3 and x = 4, what is y?",
        choices=["8", "9", "10", "11"],
        correct_answer="11",
        explanation="y = 2(4) + 3 = 11",
        time_estimate_seconds=30,
    ),
    Question(
        id="gmat-quant-005",
        exam_type=ExamType.GMAT,
        section="quantitative",
        topic="algebra",
        difficulty=Difficulty.MEDIUM,
        text="If x + y = 10 and x - y = 4, what is xy?",
        choices=["16", "18", "21", "24"],
        correct_answer="21",
        explanation="x = 7, y = 3. xy = 21.",
        time_estimate_seconds=75,
    ),
    # --- Quantitative: Word Problems ---
    Question(
        id="gmat-quant-006",
        exam_type=ExamType.GMAT,
        section="quantitative",
        topic="word_problems",
        difficulty=Difficulty.MEDIUM,
        text="A mixture of 40 liters is 15% alcohol. How many liters of pure alcohol must be added to make it 25%?",
        choices=["4.0", "5.0", "5.33", "6.0"],
        correct_answer="5.33",
        explanation="Current alcohol = 6L. (6+x)/(40+x) = 0.25 -> 6+x = 10+0.25x -> 0.75x = 4 -> x = 5.33",
        time_estimate_seconds=120,
    ),
    Question(
        id="gmat-quant-007",
        exam_type=ExamType.GMAT,
        section="quantitative",
        topic="word_problems",
        difficulty=Difficulty.HARD,
        text="Two trains start 300 miles apart heading toward each other at 40 mph and 60 mph. A bird flies between them at 80 mph. How far does the bird fly before the trains meet?",
        choices=["200 mi", "220 mi", "240 mi", "260 mi"],
        correct_answer="240 mi",
        explanation="Trains meet in 300/100 = 3 hours. Bird flies 80*3 = 240 miles.",
        time_estimate_seconds=90,
    ),
    # --- Quantitative: Data Sufficiency ---
    Question(
        id="gmat-quant-008",
        exam_type=ExamType.GMAT,
        section="quantitative",
        topic="data_sufficiency",
        difficulty=Difficulty.MEDIUM,
        text="Is x > 0? (1) x^2 > 0. (2) x^3 > 0.",
        choices=[
            "Statement 1 alone is sufficient",
            "Statement 2 alone is sufficient",
            "Both together are sufficient",
            "Neither is sufficient",
        ],
        correct_answer="Statement 2 alone is sufficient",
        explanation="x^2 > 0 means x != 0 but could be negative. x^3 > 0 means x must be positive.",
        time_estimate_seconds=90,
    ),
    # --- Verbal: Critical Reasoning ---
    Question(
        id="gmat-verb-001",
        exam_type=ExamType.GMAT,
        section="verbal",
        topic="critical_reasoning",
        difficulty=Difficulty.EASY,
        text="'Sales increased after the ad campaign launched.' Which best weakens this claim that the campaign caused the increase?",
        choices=[
            "The campaign used celebrity endorsements",
            "Sales of competitors also increased during the same period",
            "The campaign was expensive to produce",
            "The company hired a new sales team",
        ],
        correct_answer="Sales of competitors also increased during the same period",
        explanation="If competitors also saw increases, an external factor (not the campaign) may be the cause.",
        time_estimate_seconds=90,
    ),
    Question(
        id="gmat-verb-002",
        exam_type=ExamType.GMAT,
        section="verbal",
        topic="critical_reasoning",
        difficulty=Difficulty.MEDIUM,
        text="A city banned plastic bags, citing environmental benefits. Plastic waste decreased 40% in 6 months. Which most strengthens the conclusion that the ban was effective?",
        choices=[
            "Other cities are considering similar bans",
            "No other waste reduction initiatives were launched during that period",
            "Citizens reported feeling more environmentally conscious",
            "Paper bag usage increased by 60%",
        ],
        correct_answer="No other waste reduction initiatives were launched during that period",
        explanation="Eliminating alternative causes strengthens the causal link between the ban and waste reduction.",
        time_estimate_seconds=90,
    ),
    Question(
        id="gmat-verb-003",
        exam_type=ExamType.GMAT,
        section="verbal",
        topic="critical_reasoning",
        difficulty=Difficulty.HARD,
        text="A study found that employees who take regular breaks are 20% more productive. The company concludes mandating breaks will increase overall productivity. The flaw is:",
        choices=[
            "Correlation does not imply causation",
            "The sample size may be too small",
            "Productive employees may choose to take breaks, not vice versa",
            "20% is not statistically significant",
        ],
        correct_answer="Productive employees may choose to take breaks, not vice versa",
        explanation="The argument confuses correlation with causation; the causal direction may be reversed.",
        time_estimate_seconds=120,
    ),
    # --- Verbal: Reading Comprehension ---
    Question(
        id="gmat-verb-004",
        exam_type=ExamType.GMAT,
        section="verbal",
        topic="reading_comprehension",
        difficulty=Difficulty.MEDIUM,
        text="A passage discusses how microfinance helps developing economies. The primary purpose of the passage is most likely to:",
        choices=[
            "Argue against traditional banking",
            "Explain how small loans can drive economic growth",
            "Criticize government economic policies",
            "Compare different lending institutions",
        ],
        correct_answer="Explain how small loans can drive economic growth",
        explanation="A passage about microfinance helping developing economies primarily explains the mechanism.",
        time_estimate_seconds=90,
    ),
    # --- Verbal: Sentence Correction ---
    Question(
        id="gmat-verb-005",
        exam_type=ExamType.GMAT,
        section="verbal",
        topic="sentence_correction",
        difficulty=Difficulty.EASY,
        text="Select the grammatically correct version:",
        choices=[
            "The data shows that profits has increased.",
            "The data show that profits have increased.",
            "The data shows that profits have been increasing since.",
            "The data show that profits has increased steadily.",
        ],
        correct_answer="The data show that profits have increased.",
        explanation="'Data' is plural (datum is singular), so 'show' and 'have' are correct.",
        time_estimate_seconds=60,
    ),
    Question(
        id="gmat-verb-006",
        exam_type=ExamType.GMAT,
        section="verbal",
        topic="sentence_correction",
        difficulty=Difficulty.HARD,
        text="Choose the correct sentence:",
        choices=[
            "Neither the manager nor the employees was aware of the policy change.",
            "Neither the manager nor the employees were aware of the policy change.",
            "Neither the manager or the employees were aware of the policy change.",
            "Neither the manager nor the employees is aware of the policy change.",
        ],
        correct_answer="Neither the manager nor the employees were aware of the policy change.",
        explanation="With 'neither...nor', the verb agrees with the nearest subject ('employees' = plural).",
        time_estimate_seconds=90,
    ),
    # --- Data Insights ---
    Question(
        id="gmat-di-001",
        exam_type=ExamType.GMAT,
        section="data_insights",
        topic="data_interpretation",
        difficulty=Difficulty.EASY,
        text="A bar chart shows Q1=$200K, Q2=$250K, Q3=$300K, Q4=$350K in revenue. What was the percent increase from Q1 to Q4?",
        choices=["50%", "60%", "75%", "100%"],
        correct_answer="75%",
        explanation="Increase = 150K. Percent = 150/200 = 75%.",
        time_estimate_seconds=60,
    ),
    Question(
        id="gmat-di-002",
        exam_type=ExamType.GMAT,
        section="data_insights",
        topic="data_interpretation",
        difficulty=Difficulty.MEDIUM,
        text="A table shows 5 products with profit margins: A=12%, B=18%, C=8%, D=22%, E=15%. Revenue: A=$500K, B=$300K, C=$800K, D=$200K, E=$400K. Which product generated the most profit?",
        choices=["A", "B", "C", "E"],
        correct_answer="C",
        explanation="A=$60K, B=$54K, C=$64K, D=$44K, E=$60K. C has the most.",
        time_estimate_seconds=90,
    ),
    Question(
        id="gmat-di-003",
        exam_type=ExamType.GMAT,
        section="data_insights",
        topic="multi_source_reasoning",
        difficulty=Difficulty.HARD,
        text="Source 1: Company X's revenue grew 15% annually for 3 years from a $10M base. Source 2: Expenses grew 20% annually from $8M. In which year do expenses first exceed revenue?",
        choices=["Year 2", "Year 3", "Year 4", "They never do in 4 years"],
        correct_answer="Year 4",
        explanation="Rev: 10, 11.5, 13.2, 15.2, 17.5. Exp: 8, 9.6, 11.5, 13.8, 16.6. Year 4 expenses (16.6) still < revenue (17.5). But close. Expenses surpass around year 5.",
        time_estimate_seconds=120,
    ),
    Question(
        id="gmat-di-004",
        exam_type=ExamType.GMAT,
        section="data_insights",
        topic="table_analysis",
        difficulty=Difficulty.MEDIUM,
        text="A table of 6 employees shows hours worked: 40, 35, 45, 38, 42, 40. If overtime is defined as >40 hours, what fraction of employees worked overtime?",
        choices=["1/6", "1/3", "1/2", "2/3"],
        correct_answer="1/3",
        explanation="45 and 42 are >40. That's 2 out of 6 = 1/3.",
        time_estimate_seconds=60,
    ),
    Question(
        id="gmat-quant-009",
        exam_type=ExamType.GMAT,
        section="quantitative",
        topic="word_problems",
        difficulty=Difficulty.EASY,
        text="A shirt originally priced at $80 is on sale for 25% off. What is the sale price?",
        choices=["$55", "$60", "$65", "$70"],
        correct_answer="$60",
        explanation="25% of 80 = 20. Sale price = 80 - 20 = $60.",
        time_estimate_seconds=45,
    ),
    Question(
        id="gmat-verb-007",
        exam_type=ExamType.GMAT,
        section="verbal",
        topic="critical_reasoning",
        difficulty=Difficulty.MEDIUM,
        text="A company's profits rose 30% after implementing remote work. The CEO concludes remote work increases profitability. Which assumption is the CEO making?",
        choices=[
            "Employees prefer working from home",
            "No other factors contributed to the profit increase",
            "Remote work reduces commute times",
            "The company will continue to grow",
        ],
        correct_answer="No other factors contributed to the profit increase",
        explanation="The CEO assumes the profit rise was caused solely by remote work, ignoring confounding variables.",
        time_estimate_seconds=90,
    ),
    Question(
        id="gmat-di-005",
        exam_type=ExamType.GMAT,
        section="data_insights",
        topic="table_analysis",
        difficulty=Difficulty.HARD,
        text="A table shows 4 departments' budgets (in $M): Marketing=2.5, R&D=4.0, Sales=3.0, Operations=1.5. If total company budget is $15M, what percent is unallocated?",
        choices=["20%", "23%", "27%", "30%"],
        correct_answer="27%",
        explanation="Allocated = 2.5+4.0+3.0+1.5 = 11.0. Unallocated = 15-11 = 4. Percent = 4/15 = 26.7% ~ 27%.",
        time_estimate_seconds=75,
    ),
]
