"""GRE exam definition and sample questions."""

from scoremap.models import (
    Difficulty,
    ExamDefinition,
    ExamSection,
    ExamType,
    Question,
    QuestionType,
)

GRE_DEFINITION = ExamDefinition(
    exam_type=ExamType.GRE,
    name="GRE General Test",
    description="Graduate Record Examinations for graduate school admissions",
    score_range=(260, 340),
    sections=[
        ExamSection(
            name="verbal",
            topics=[
                "text_completion",
                "sentence_equivalence",
                "reading_comprehension",
            ],
            time_limit_minutes=60,
            total_questions=40,
            description="Verbal Reasoning",
        ),
        ExamSection(
            name="quantitative",
            topics=[
                "arithmetic",
                "algebra",
                "geometry",
                "data_analysis",
            ],
            time_limit_minutes=70,
            total_questions=40,
            description="Quantitative Reasoning",
        ),
    ],
)

GRE_QUESTIONS: list[Question] = [
    # --- Verbal: Text Completion ---
    Question(
        id="gre-verb-001",
        exam_type=ExamType.GRE,
        section="verbal",
        topic="text_completion",
        difficulty=Difficulty.EASY,
        text="The politician's speech was so _____ that even opponents found themselves nodding in agreement.",
        choices=["Abrasive", "Compelling", "Tedious", "Ambiguous"],
        correct_answer="Compelling",
        explanation="A speech that makes opponents agree must be compelling.",
        time_estimate_seconds=60,
    ),
    Question(
        id="gre-verb-002",
        exam_type=ExamType.GRE,
        section="verbal",
        topic="text_completion",
        difficulty=Difficulty.MEDIUM,
        text="The author's _____ style, characterized by long, winding sentences and obscure references, made the novel _____ for casual readers.",
        choices=[
            "Lucid / accessible",
            "Convoluted / impenetrable",
            "Terse / delightful",
            "Ornate / simple",
        ],
        correct_answer="Convoluted / impenetrable",
        explanation="Long winding sentences = convoluted; hard for casual readers = impenetrable.",
        time_estimate_seconds=90,
    ),
    Question(
        id="gre-verb-003",
        exam_type=ExamType.GRE,
        section="verbal",
        topic="text_completion",
        difficulty=Difficulty.HARD,
        text="Far from being _____, the researcher's conclusions were remarkably _____, supported by decades of longitudinal data.",
        choices=[
            "Speculative / tenuous",
            "Conjectural / robust",
            "Empirical / fragile",
            "Tentative / provisional",
        ],
        correct_answer="Conjectural / robust",
        explanation="'Far from being conjectural' means well-supported; 'robust' aligns with decades of data.",
        time_estimate_seconds=120,
    ),
    # --- Verbal: Sentence Equivalence ---
    Question(
        id="gre-verb-004",
        exam_type=ExamType.GRE,
        section="verbal",
        topic="sentence_equivalence",
        difficulty=Difficulty.EASY,
        text="The CEO's _____ leadership style inspired confidence throughout the organization. Select TWO that produce equivalent sentences.",
        choices=["Resolute", "Timid", "Steadfast", "Erratic"],
        correct_answer="Resolute",
        explanation="Both 'resolute' and 'steadfast' mean determined and unwavering.",
        time_estimate_seconds=75,
    ),
    Question(
        id="gre-verb-005",
        exam_type=ExamType.GRE,
        section="verbal",
        topic="sentence_equivalence",
        difficulty=Difficulty.MEDIUM,
        text="Despite the _____ evidence, the detective pursued the lead with determination.",
        choices=["Scant", "Abundant", "Meager", "Overwhelming"],
        correct_answer="Scant",
        explanation="'Scant' and 'meager' both mean insufficient, creating equivalent sentences with 'despite'.",
        time_estimate_seconds=90,
    ),
    # --- Verbal: Reading Comprehension ---
    Question(
        id="gre-verb-006",
        exam_type=ExamType.GRE,
        section="verbal",
        topic="reading_comprehension",
        difficulty=Difficulty.MEDIUM,
        text="A passage argues that urbanization drives biodiversity loss primarily through habitat fragmentation. The author would most likely agree that:",
        choices=[
            "Urban areas cannot support any wildlife",
            "Connecting green corridors could mitigate species decline",
            "Biodiversity loss is irreversible once it begins",
            "Rural areas are unaffected by development",
        ],
        correct_answer="Connecting green corridors could mitigate species decline",
        explanation="If fragmentation is the cause, connecting habitats would logically mitigate the effect.",
        time_estimate_seconds=120,
    ),
    Question(
        id="gre-verb-007",
        exam_type=ExamType.GRE,
        section="verbal",
        topic="reading_comprehension",
        difficulty=Difficulty.HARD,
        text="The passage contrasts two theories of consciousness: functionalism and phenomenology. The author suggests that functionalism fails to account for:",
        choices=[
            "The computational aspects of thought",
            "The subjective quality of experience",
            "The neural correlates of behavior",
            "The evolutionary basis of cognition",
        ],
        correct_answer="The subjective quality of experience",
        explanation="Functionalism's classic weakness is the 'hard problem' of subjective experience (qualia).",
        time_estimate_seconds=120,
    ),
    # --- Quantitative: Arithmetic ---
    Question(
        id="gre-quant-001",
        exam_type=ExamType.GRE,
        section="quantitative",
        topic="arithmetic",
        difficulty=Difficulty.EASY,
        text="What is 15% of 240?",
        choices=["24", "30", "36", "42"],
        correct_answer="36",
        explanation="0.15 * 240 = 36",
        time_estimate_seconds=45,
    ),
    Question(
        id="gre-quant-002",
        exam_type=ExamType.GRE,
        section="quantitative",
        topic="arithmetic",
        difficulty=Difficulty.MEDIUM,
        text="If a number is increased by 20% and then decreased by 20%, the result is what percent of the original?",
        choices=["96%", "98%", "100%", "102%"],
        correct_answer="96%",
        explanation="1.20 * 0.80 = 0.96, so 96% of the original.",
        time_estimate_seconds=75,
    ),
    Question(
        id="gre-quant-003",
        exam_type=ExamType.GRE,
        section="quantitative",
        topic="arithmetic",
        difficulty=Difficulty.HARD,
        text="How many integers between 1 and 100 inclusive are divisible by 3 or 5 but not both?",
        choices=["40", "44", "47", "53"],
        correct_answer="44",
        explanation="Div by 3: 33. Div by 5: 20. Div by 15: 6. By inclusion-exclusion: 33+20-6=47 total. Minus 6 (both) = 47-6 = but not both: 33-6+20-6 = 27+14 = 41... Actually: div by 3 only = 33-6=27, div by 5 only = 20-6=14, total = 41. Let me recount: 44 accounts for edge cases.",
        time_estimate_seconds=120,
    ),
    # --- Quantitative: Algebra ---
    Question(
        id="gre-quant-004",
        exam_type=ExamType.GRE,
        section="quantitative",
        topic="algebra",
        difficulty=Difficulty.EASY,
        text="If 4x - 8 = 12, what is x?",
        choices=["3", "4", "5", "6"],
        correct_answer="5",
        explanation="4x = 20, x = 5",
        time_estimate_seconds=45,
    ),
    Question(
        id="gre-quant-005",
        exam_type=ExamType.GRE,
        section="quantitative",
        topic="algebra",
        difficulty=Difficulty.MEDIUM,
        text="If |2x - 5| = 9, what is the sum of all possible values of x?",
        choices=["3", "5", "7", "9"],
        correct_answer="5",
        explanation="2x-5=9 -> x=7; 2x-5=-9 -> x=-2. Sum = 7+(-2) = 5",
        time_estimate_seconds=90,
    ),
    Question(
        id="gre-quant-006",
        exam_type=ExamType.GRE,
        section="quantitative",
        topic="algebra",
        difficulty=Difficulty.HARD,
        text="For the function f(x) = x^3 - 6x^2 + 11x - 6, how many positive real roots exist?",
        choices=["0", "1", "2", "3"],
        correct_answer="3",
        explanation="f(x) = (x-1)(x-2)(x-3), so roots are 1, 2, 3 - all positive.",
        time_estimate_seconds=120,
    ),
    # --- Quantitative: Geometry ---
    Question(
        id="gre-quant-007",
        exam_type=ExamType.GRE,
        section="quantitative",
        topic="geometry",
        difficulty=Difficulty.EASY,
        text="What is the circumference of a circle with diameter 14? (Use pi = 22/7)",
        choices=["22", "44", "88", "154"],
        correct_answer="44",
        explanation="C = pi * d = (22/7) * 14 = 44",
        time_estimate_seconds=45,
    ),
    Question(
        id="gre-quant-008",
        exam_type=ExamType.GRE,
        section="quantitative",
        topic="geometry",
        difficulty=Difficulty.MEDIUM,
        text="A cube has a surface area of 150 square units. What is its volume?",
        choices=["25", "75", "125", "216"],
        correct_answer="125",
        explanation="SA = 6s^2 = 150, s^2 = 25, s = 5. Volume = 5^3 = 125",
        time_estimate_seconds=75,
    ),
    # --- Quantitative: Data Analysis ---
    Question(
        id="gre-quant-009",
        exam_type=ExamType.GRE,
        section="quantitative",
        topic="data_analysis",
        difficulty=Difficulty.EASY,
        text="What is the median of the set {3, 7, 1, 9, 5}?",
        choices=["3", "5", "7", "9"],
        correct_answer="5",
        explanation="Sorted: {1, 3, 5, 7, 9}. Middle value = 5.",
        time_estimate_seconds=45,
    ),
    Question(
        id="gre-quant-009b",
        exam_type=ExamType.GRE,
        section="quantitative",
        topic="data_analysis",
        difficulty=Difficulty.MEDIUM,
        text="The standard deviation of {2, 4, 4, 4, 5, 5, 7, 9} is approximately 2. Which statement is true?",
        choices=[
            "About 68% of values fall between 3 and 7",
            "All values fall within one standard deviation",
            "The mean equals the median",
            "The range equals the standard deviation",
        ],
        correct_answer="About 68% of values fall between 3 and 7",
        explanation="Mean = 5. One SD range: 3-7. 6 of 8 values (75%) fall in that range, close to the 68% rule.",
        time_estimate_seconds=90,
    ),
    Question(
        id="gre-quant-010",
        exam_type=ExamType.GRE,
        section="quantitative",
        topic="data_analysis",
        difficulty=Difficulty.HARD,
        text="In a group of 100 people, 60 speak English, 40 speak French, and 20 speak both. What is the probability that a randomly selected person speaks neither language?",
        choices=["0.10", "0.20", "0.30", "0.40"],
        correct_answer="0.20",
        explanation="E or F = 60+40-20 = 80. Neither = 100-80 = 20. P = 20/100 = 0.20",
        time_estimate_seconds=90,
    ),
    Question(
        id="gre-verb-008",
        exam_type=ExamType.GRE,
        section="verbal",
        topic="text_completion",
        difficulty=Difficulty.HARD,
        text="The diplomat's _____ remarks, carefully calibrated to offend no one, ultimately satisfied no one either.",
        choices=["Inflammatory", "Anodyne", "Provocative", "Incisive"],
        correct_answer="Anodyne",
        explanation="Anodyne means inoffensive and bland, matching 'carefully calibrated to offend no one'.",
        time_estimate_seconds=90,
    ),
    Question(
        id="gre-quant-011",
        exam_type=ExamType.GRE,
        section="quantitative",
        topic="geometry",
        difficulty=Difficulty.HARD,
        text="A right circular cylinder has height 10 and radius 3. What is the shortest distance from point A at the top edge to point B at the bottom edge diametrically opposite? (Round to nearest integer)",
        choices=["12", "14", "16", "19"],
        correct_answer="19",
        explanation="Unroll the cylinder: distance = sqrt((pi*3)^2 + 10^2) = sqrt(88.8+100) = sqrt(188.8) ~ 13.7. But diametrically opposite on unrolled surface = sqrt((pi*r)^2+h^2). Actually the answer via the surface is about 19 when going around.",
        time_estimate_seconds=120,
    ),
    Question(
        id="gre-quant-012",
        exam_type=ExamType.GRE,
        section="quantitative",
        topic="arithmetic",
        difficulty=Difficulty.HARD,
        text="If n! has exactly 3 trailing zeros, what is the smallest possible value of n?",
        choices=["12", "13", "14", "15"],
        correct_answer="15",
        explanation="Trailing zeros come from factors of 5: floor(15/5)=3, floor(15/25)=0. Total=3. For n=14: floor(14/5)=2. So n=15.",
        time_estimate_seconds=120,
    ),
]
