"""SAT exam definition and sample questions."""

from scoremap.models import (
    Difficulty,
    ExamDefinition,
    ExamSection,
    ExamType,
    Question,
    QuestionType,
)

SAT_DEFINITION = ExamDefinition(
    exam_type=ExamType.SAT,
    name="SAT",
    description="College admissions standardized test",
    score_range=(400, 1600),
    sections=[
        ExamSection(
            name="math",
            topics=[
                "algebra",
                "advanced_math",
                "problem_solving",
                "geometry_trig",
            ],
            time_limit_minutes=70,
            total_questions=44,
            description="Math section covering algebra through advanced topics",
        ),
        ExamSection(
            name="reading_writing",
            topics=[
                "reading_comprehension",
                "vocabulary",
                "grammar",
                "rhetoric",
            ],
            time_limit_minutes=64,
            total_questions=54,
            description="Evidence-based reading and writing",
        ),
    ],
)

SAT_QUESTIONS: list[Question] = [
    # --- Math: Algebra (easy/medium/hard) ---
    Question(
        id="sat-math-001",
        exam_type=ExamType.SAT,
        section="math",
        topic="algebra",
        difficulty=Difficulty.EASY,
        text="If 3x + 7 = 22, what is the value of x?",
        choices=["3", "4", "5", "6"],
        correct_answer="5",
        explanation="3x + 7 = 22 -> 3x = 15 -> x = 5",
        time_estimate_seconds=60,
    ),
    Question(
        id="sat-math-002",
        exam_type=ExamType.SAT,
        section="math",
        topic="algebra",
        difficulty=Difficulty.MEDIUM,
        text="If 2(x - 3) + 4 = 3x - 1, what is x?",
        choices=["1", "-1", "3", "-3"],
        correct_answer="-1",
        explanation="2x - 6 + 4 = 3x - 1 -> 2x - 2 = 3x - 1 -> -1 = x",
        time_estimate_seconds=90,
    ),
    Question(
        id="sat-math-003",
        exam_type=ExamType.SAT,
        section="math",
        topic="algebra",
        difficulty=Difficulty.HARD,
        text="For what value of k does the system 2x + ky = 6 and kx + 8y = 12 have infinitely many solutions?",
        choices=["2", "4", "6", "8"],
        correct_answer="4",
        explanation="For infinitely many solutions: 2/k = k/8 = 6/12 -> k^2 = 16 -> k = 4",
        time_estimate_seconds=120,
    ),
    # --- Math: Advanced Math ---
    Question(
        id="sat-math-004",
        exam_type=ExamType.SAT,
        section="math",
        topic="advanced_math",
        difficulty=Difficulty.EASY,
        text="What is the value of x^2 - 4 when x = 3?",
        choices=["3", "5", "7", "9"],
        correct_answer="5",
        explanation="3^2 - 4 = 9 - 4 = 5",
        time_estimate_seconds=45,
    ),
    Question(
        id="sat-math-005",
        exam_type=ExamType.SAT,
        section="math",
        topic="advanced_math",
        difficulty=Difficulty.MEDIUM,
        text="If f(x) = x^2 - 5x + 6, which values of x satisfy f(x) = 0?",
        choices=["1 and 6", "2 and 3", "-2 and -3", "3 and 6"],
        correct_answer="2 and 3",
        explanation="x^2 - 5x + 6 = (x-2)(x-3) = 0 -> x = 2 or x = 3",
        time_estimate_seconds=90,
    ),
    Question(
        id="sat-math-006",
        exam_type=ExamType.SAT,
        section="math",
        topic="advanced_math",
        difficulty=Difficulty.HARD,
        text="If g(x) = 2x^3 - 3x^2 - 12x + 5, at how many points does the graph of g change direction?",
        choices=["0", "1", "2", "3"],
        correct_answer="2",
        explanation="g'(x) = 6x^2 - 6x - 12 = 6(x^2-x-2) = 6(x-2)(x+1). Two critical points => 2 direction changes.",
        time_estimate_seconds=120,
    ),
    # --- Math: Problem Solving ---
    Question(
        id="sat-math-007",
        exam_type=ExamType.SAT,
        section="math",
        topic="problem_solving",
        difficulty=Difficulty.EASY,
        text="A store sells notebooks for $3 each. If Maria buys 7 notebooks and pays with a $25 bill, how much change does she receive?",
        choices=["$2", "$3", "$4", "$5"],
        correct_answer="$4",
        explanation="7 * 3 = 21; 25 - 21 = 4",
        time_estimate_seconds=45,
    ),
    Question(
        id="sat-math-008",
        exam_type=ExamType.SAT,
        section="math",
        topic="problem_solving",
        difficulty=Difficulty.MEDIUM,
        text="The average of five numbers is 14. If four of the numbers are 10, 12, 16, and 18, what is the fifth number?",
        choices=["12", "14", "16", "18"],
        correct_answer="14",
        explanation="Sum = 5*14 = 70. 10+12+16+18 = 56. Fifth = 70-56 = 14",
        time_estimate_seconds=75,
    ),
    # --- Math: Geometry/Trig ---
    Question(
        id="sat-math-009",
        exam_type=ExamType.SAT,
        section="math",
        topic="geometry_trig",
        difficulty=Difficulty.EASY,
        text="What is the area of a rectangle with length 8 and width 5?",
        choices=["26", "40", "13", "80"],
        correct_answer="40",
        explanation="Area = length * width = 8 * 5 = 40",
        time_estimate_seconds=30,
    ),
    Question(
        id="sat-math-010",
        exam_type=ExamType.SAT,
        section="math",
        topic="geometry_trig",
        difficulty=Difficulty.MEDIUM,
        text="In a right triangle, one leg is 6 and the hypotenuse is 10. What is the length of the other leg?",
        choices=["4", "6", "8", "12"],
        correct_answer="8",
        explanation="a^2 + 6^2 = 10^2 -> a^2 = 100 - 36 = 64 -> a = 8",
        time_estimate_seconds=60,
    ),
    Question(
        id="sat-math-011",
        exam_type=ExamType.SAT,
        section="math",
        topic="geometry_trig",
        difficulty=Difficulty.HARD,
        text="A circle has its center at (3, 4) and passes through the origin. What is the radius?",
        choices=["3", "4", "5", "7"],
        correct_answer="5",
        explanation="Distance from (3,4) to (0,0) = sqrt(9+16) = sqrt(25) = 5",
        time_estimate_seconds=90,
    ),
    # --- Reading/Writing: Reading Comprehension ---
    Question(
        id="sat-rw-001",
        exam_type=ExamType.SAT,
        section="reading_writing",
        topic="reading_comprehension",
        difficulty=Difficulty.EASY,
        text='In the sentence "The scientist\'s groundbreaking discovery revolutionized the field," what does "groundbreaking" most nearly mean?',
        choices=["Digging soil", "Innovative", "Destructive", "Ordinary"],
        correct_answer="Innovative",
        explanation="Groundbreaking in context means pioneering or innovative.",
        time_estimate_seconds=45,
    ),
    Question(
        id="sat-rw-002",
        exam_type=ExamType.SAT,
        section="reading_writing",
        topic="reading_comprehension",
        difficulty=Difficulty.MEDIUM,
        text='A passage states: "Despite initial skepticism, the theory gained widespread acceptance after rigorous peer review." What can be inferred about the theory?',
        choices=[
            "It was immediately accepted",
            "It was never proven",
            "It withstood scientific scrutiny",
            "It was rejected by peers",
        ],
        correct_answer="It withstood scientific scrutiny",
        explanation="Gaining acceptance after rigorous peer review implies it withstood scrutiny.",
        time_estimate_seconds=90,
    ),
    Question(
        id="sat-rw-003",
        exam_type=ExamType.SAT,
        section="reading_writing",
        topic="reading_comprehension",
        difficulty=Difficulty.HARD,
        text='An author writes: "The ostensible purpose of the legislation was environmental protection, yet its primary beneficiaries were industrial conglomerates." The author\'s tone is best described as:',
        choices=["Neutral", "Celebratory", "Skeptical", "Indifferent"],
        correct_answer="Skeptical",
        explanation="The contrast between 'ostensible purpose' and 'primary beneficiaries' reveals skepticism.",
        time_estimate_seconds=90,
    ),
    # --- Reading/Writing: Vocabulary ---
    Question(
        id="sat-rw-004",
        exam_type=ExamType.SAT,
        section="reading_writing",
        topic="vocabulary",
        difficulty=Difficulty.EASY,
        text="Choose the word that best completes: 'The _____ weather forced the cancellation of the outdoor event.'",
        choices=["Clement", "Inclement", "Temperate", "Balmy"],
        correct_answer="Inclement",
        explanation="Inclement means harsh weather that would force cancellation.",
        time_estimate_seconds=45,
    ),
    Question(
        id="sat-rw-004b",
        exam_type=ExamType.SAT,
        section="reading_writing",
        topic="vocabulary",
        difficulty=Difficulty.MEDIUM,
        text="The researcher's _____ approach to data collection ensured no detail was overlooked.",
        choices=["Cursory", "Meticulous", "Haphazard", "Negligent"],
        correct_answer="Meticulous",
        explanation="Meticulous means showing great attention to detail.",
        time_estimate_seconds=60,
    ),
    # --- Reading/Writing: Grammar ---
    Question(
        id="sat-rw-005",
        exam_type=ExamType.SAT,
        section="reading_writing",
        topic="grammar",
        difficulty=Difficulty.EASY,
        text="Which sentence is grammatically correct?",
        choices=[
            "Each of the students have their own book.",
            "Each of the students has his or her own book.",
            "Each of the students are having their own book.",
            "Each of the students were given their books.",
        ],
        correct_answer="Each of the students has his or her own book.",
        explanation="'Each' is singular, requiring the singular verb 'has'.",
        time_estimate_seconds=60,
    ),
    Question(
        id="sat-rw-006",
        exam_type=ExamType.SAT,
        section="reading_writing",
        topic="grammar",
        difficulty=Difficulty.MEDIUM,
        text='Identify the error: "The committee have decided that their next meeting will be postponed until further notice."',
        choices=[
            "'have' should be 'has'",
            "'their' should be 'its'",
            "Both A and B",
            "No error",
        ],
        correct_answer="Both A and B",
        explanation="'Committee' is a collective noun (singular in American English), needing 'has' and 'its'.",
        time_estimate_seconds=75,
    ),
    # --- Reading/Writing: Rhetoric ---
    Question(
        id="sat-rw-007",
        exam_type=ExamType.SAT,
        section="reading_writing",
        topic="rhetoric",
        difficulty=Difficulty.MEDIUM,
        text="Which transition best connects these sentences? 'The experiment yielded unexpected results. _____, the team decided to redesign the study.'",
        choices=["Moreover", "Consequently", "Nevertheless", "Similarly"],
        correct_answer="Consequently",
        explanation="'Consequently' indicates a cause-effect relationship between the unexpected results and the redesign.",
        time_estimate_seconds=60,
    ),
    Question(
        id="sat-rw-008",
        exam_type=ExamType.SAT,
        section="reading_writing",
        topic="rhetoric",
        difficulty=Difficulty.HARD,
        text="An essay argues that renewable energy is essential. Which evidence would LEAST strengthen this argument?",
        choices=[
            "Statistics on declining fossil fuel reserves",
            "Data on solar panel cost reductions",
            "A celebrity's endorsement of green living",
            "Research on carbon emission health effects",
        ],
        correct_answer="A celebrity's endorsement of green living",
        explanation="A celebrity endorsement is an appeal to authority, not substantive evidence.",
        time_estimate_seconds=90,
    ),
]
